import type { ScanResponse } from "@/types/scan";

export function downloadReport(scan: ScanResponse): void {
  const md = buildMarkdownReport(scan);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `agentlens-report-${scan.id.slice(0, 8)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildMarkdownReport(scan: ScanResponse): string {
  const d = scan.doctor_result;
  const o = scan.optimization_result;
  const b = scan.benchmark_result;
  const f = scan.framework_result;
  const a = scan.agent_result;

  const lines: string[] = [
    `# AgentLens AI — Diagnostic Report`,
    ``,
    `**Repository:** ${scan.source_ref}`,
    `**Scanned:** ${new Date(scan.created_at).toLocaleString()}`,
    `**Framework:** ${f?.primary_framework ?? "Not detected"}`,
    ``,
    `## Health Score: ${d?.health_score ?? "N/A"}/100`,
    ``,
  ];

  if (d) {
    lines.push(`| Subscore | Score |`, `|---|---|`);
    for (const [key, value] of Object.entries(d.subscores)) {
      lines.push(`| ${key} | ${value} |`);
    }
    lines.push(``, `**Estimated token savings:** ${d.total_estimated_savings_tokens.toLocaleString()} tokens`, ``);
  }

  if (a) {
    lines.push(
      `## Architecture`,
      ``,
      `- Agents: ${a.agent_count}`,
      `- Prompts: ${a.prompt_count}`,
      `- LLM calls: ${a.llm_call_count}`,
      `- Memory components: ${a.memory_component_count}`,
      `- Tools: ${a.tool_count}`,
      `- RAG pipelines: ${a.rag_pipeline_count}`,
      ``,
    );
  }

  if (d && d.issues.length > 0) {
    lines.push(`## Issues (${d.issues.length})`, ``);
    for (const issue of d.issues) {
      lines.push(
        `### [${issue.severity.toUpperCase()}] ${issue.title}`,
        `**File:** ${issue.file}${issue.line ? `:${issue.line}` : ""}`,
        ``,
        issue.explanation,
        ``,
        `**Suggested fix:** ${issue.suggested_fix}`,
        `**Expected savings:** ${issue.expected_token_savings} tokens`,
        ``,
      );
    }
  }

  if (o) {
    lines.push(
      `## Paritok Optimization`,
      ``,
      `- Engine: ${o.engine}`,
      `- Overall compression: ${o.overall_compression_pct}%`,
      `- Tokens: ${o.total_original_tokens.toLocaleString()} → ${o.total_compressed_tokens.toLocaleString()}`,
      ``,
    );
  }

  if (b) {
    lines.push(
      `## Benchmark (Before vs. After)`,
      ``,
      `| Metric | Original | Optimized | Reduction |`,
      `|---|---|---|---|`,
      `| Tokens | ${b.pipeline_a.total_tokens.toLocaleString()} | ${b.pipeline_b.total_tokens.toLocaleString()} | ${b.token_reduction_pct}% |`,
      `| Cost (USD/session) | $${b.pipeline_a.estimated_cost_usd.toFixed(4)} | $${b.pipeline_b.estimated_cost_usd.toFixed(4)} | ${b.cost_reduction_pct}% |`,
      `| Latency (ms) | ${b.pipeline_a.estimated_latency_ms} | ${b.pipeline_b.estimated_latency_ms} | ${b.latency_reduction_pct}% |`,
      ``,
    );
  }

  lines.push(`---`, `_Generated by AgentLens AI — Paritok Token Efficiency Hackathon_`);

  return lines.join("\n");
}
